"""Add difficulty column to users

Revision ID: aadecd7233e1
Revises: 69fddc870ba3
Create Date: 2024-12-08 20:10:54.759756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aadecd7233e1'
down_revision = '69fddc870ba3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('difficulty', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('difficulty')

    # ### end Alembic commands ###
